qgis_deployment_toolbelt/cli.py
tests/test_cli_main.py

Replace the variable scenario by scenario_filepath

---

qgis_deployment_toolbelt/profiles/remote_git_handler.py

Make the remote git handler much more robust to 

---

.gitignore
docs/jobs/index.md
docs/jobs/plugins_downloader.md
docs/jobs/plugins_synchronizer.md
qgis_deployment_toolbelt/jobs/job_plugins_downloader.py
qgis_deployment_toolbelt/jobs/job_plugins_synchronizer.py
qgis_deployment_toolbelt/jobs/orchestrator.py
qgis_deployment_toolbelt/plugins/plugin.py
qgis_deployment_toolbelt/profiles/qdt_profile.py
qgis_deployment_toolbelt/utils/file_downloader.py
scenario.qdt.yml
tests/fixtures/profiles/good_profile_complete.json
tests/fixtures/profiles/good_profile_minimal.json
tests/test_qdt_profile_object.py
tests/test_qplugin_object.py

Feature: plugins synchronization - part 1/2

---

qgis_deployment_toolbelt/commands/cli_upgrade.py
requirements/base.txt
tests/test_about.py

https://packaging.pypa.io/ instead of https://python-semver.readthedocs.io/en/stable/

Dependencies: replace semver by packaging to compare versions

---

.github/workflows/tests.yml
qgis_deployment_toolbelt/commands/upgrade.py
qgis_deployment_toolbelt/utils/file_downloader.py
tests/test_cli_upgrade.py

- handle GitHub Token if environment variable `GITHUB_TOKEN` is set to avoid API rate limit
- improve headers (user-agent and content-type)
- add test against GitHub release management

Improve upgrade subcommand by handling GitHub Token

---

docs/jobs/profiles_manager.md
docs/schemas/profile/qgis_plugin.json
qgis_deployment_toolbelt/jobs/job_plugins_downloader.py
qgis_deployment_toolbelt/plugins/plugin.py
tests/test_qplugin_object.py

Until now, only "remote" plugins were managed. This PR adds ability to copy plugins stored locally.
Typically in a `profile.json`:
```json
{
"$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
"name": "basic",
"author": "QDT Dev Team",
"email": "qgis@oslandia.com",
"icon": "images/qgis.ico",
"splash": "images/splash.png",
"qgisMinimumVersion": "3.16",
"qgisMaximumVersion": "3.30",
"version": "1.0.0",
"plugins": [
{
"name": "Spreadsheet Layers",
"folder_name": "SpreadsheetLayers",
"official_repository": true,
"plugin_id": 766,
"version": "2.0.0"
},
{
"name": "Custom intra plugin",
"folder_name": "intra_plugin",
"official_repository": false,
"plugin_id": 202303,
"location": "local",
"url": "S://QGIS//plugins//intra-plugin.zip"

Feature: handle "local" plugins

---

docs/jobs/environment_variables.md
docs/schemas/scenario/jobs/manage-env-vars.json
qgis_deployment_toolbelt/jobs/job_environment_variables.py
qgis_deployment_toolbelt/utils/url_helpers.py
tests/test_job_environment_variables.py
tests/test_utils_url_helpers.py

To avoid ambiguity, it adds an option to the [Environment variables manager job](https://guts.github.io/qgis-deployment-cli/jobs/environment_variables.html) allowing user to specify value type:
```yaml
- name: Set environment variables
uses: manage-env-vars
with:
- name: HTTP_PROXY
action: "add"
scope: "user"
value: "http://proxy.qdt.fr:8080"
value_type: url
- name: HTTPS_PROXY
action: "add"
scope: "user"
value: "https://proxy.qdtfr:443"
value_type: url
- name: DISABLE_SSL
action: "add"
scope: "user"
value: False
value_type: bool
- name: PYQGIS_STARTUP
action: "add"
scope: "user"
value: "~/qgis/startup.py"
value_type: path
```
Closes #290

Fix: accept different types (URLs or str) as environment variables values

---

.github/workflows/build_release.yml
.gitignore
builder/pyinstaller_build_macos.py
builder/pyinstaller_build_ubuntu.py
builder/pyinstaller_build_windows.py
docs/development/packaging.md

- change executable name from ` QGISDeploymentToolbelt_0-26-0_Windows64bit_Python3-11.exe ` to `QGISDeploymentToolbelt_0-26-0.exe` cc @jmkerloch 
- let PyInstaller deciding use UPX or not
- generate a build report to keep a trace accross CI/CD
- minor improvments in builder scripts (f-strings...)
- update packaging documentation consequently

Packaging: improve output name and PyInstaller options

---

setup.py

Make license classifiers compatible with PyPI to fix error during publishing (https://github.com/Guts/qgis-deployment-cli/actions/runs/6799893590/job/18487221639):
Upstream:
- https://github.com/pypi/legacy/issues/91
- https://github.com/pypa/trove-classifiers/issues/17

Packaging: renamed license to match Pypi classifier

---

.github/workflows/build_release.yml

Trusted Publishers is the latest secured (OpenID Connect) way to publish to PyPi. It does not require to store any credential or token in GitHub.
For more information, see: https://docs.pypi.org/trusted-publishers/

Publishing to PyPi: switch to trusted publisher

---

builder/pyinstaller_build_macos.py
builder/pyinstaller_build_ubuntu.py
builder/pyinstaller_build_windows.py
docs/development/packaging.md

Because names are used in upgrade command to retrieve the matching operating system release's asset.
I've created an issue in the GitHub Action used to publish to GitHub Release to set label property: https://github.com/softprops/action-gh-release/issues/394

Packaging: restore operating system name in final executables

---

examples/profiles/Viewer Mode/QGIS/QGISCUSTOMIZATION3.ini
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/profiles/git_handler_base.py
qgis_deployment_toolbelt/profiles/local_git_handler.py
qgis_deployment_toolbelt/profiles/remote_git_handler.py
tests/dev/dev_dulwich_remote.py
tests/test_git_handler.py

- add a class `GitHandlerBase` and make `LocalGitHandler` and `RemoteGitHandler` inherit from to mutualize code
- fix profiles sync which was stucked during fetch

Refacto: add a Git handler base class to inherit from and avoid duplicate code

---

qgis_deployment_toolbelt/utils/proxies.py
tests/test_utils_proxies.py

Extracted evolution from #294 which add a convenient `get_proxy_handler` function and cache recurring functions.

feature: add util to get ProxyHandler and cache some recurring functions

---

qgis_deployment_toolbelt/utils/file_downloader.py

Extracted evolution from https://github.com/Guts/qgis-deployment-cli/pull/294 and following #358 to use the `get_proxy_handler` in file downloader.

feature: use proxy handler in file downloader

---

qgis_deployment_toolbelt/utils/simple_http_client.py
tests/test_utils_proxies.py
tests/test_utils_simple_http_client.py

Extracted evolution from https://github.com/Guts/qgis-deployment-cli/pull/294 and following https://github.com/Guts/qgis-deployment-cli/pull/358 to embed a simple http client exclusively based on standard library.

feature: add simple http client

---

qgis_deployment_toolbelt/utils/journalizer.py

Typical example:
```python
2023-12-22 19:51:53||INFO||journalizer||132||========== QGIS Deployment Toolbelt - 0.29.0 ==========
2023-12-22 19:51:53||DEBUG||journalizer||133||Operating System: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
2023-12-22 19:51:53||DEBUG||journalizer||135||Distribution name and version: Ubuntu 22.04
2023-12-22 19:51:53||DEBUG||journalizer||138||Architecture: 64bit
[...]
```

log: on Linux, add distribution name and version

---

examples/scenarios/demo-scenario.qdt.yml
qgis_deployment_toolbelt/commands/deployment.py
qgis_deployment_toolbelt/constants.py
qgis_deployment_toolbelt/jobs/generic_job.py
qgis_deployment_toolbelt/jobs/job_plugins_downloader.py
qgis_deployment_toolbelt/jobs/job_plugins_synchronizer.py
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/jobs/orchestrator.py
qgis_deployment_toolbelt/utils/journalizer.py

This PR aims to improve how QDT organizes its proper local folder, moving downloaded profiles (repositores) into a specific folder.

Change: move QDT subfolders to generic job

---

requirements/testing.txt

Not a real problme since it's just a test dependency. Still here comes the fix for https://github.com/Guts/qgis-deployment-cli/security/dependabot/2
> Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).

security: bump pillow to 10.2 to fix CVE-2022-22817

---

examples/profiles/Viewer Mode/profile.json
qgis_deployment_toolbelt/plugins/plugin.py
tests/fixtures/profiles/good_profile_complete.json
tests/fixtures/profiles/good_sample_profile.json
tests/test_qplugin_object.py

The plugin changed its versioning scheme on plugins repository without any warning so it breaks out the referring profiles (examples, tests...).
This PR fixes that.
cc @xcaeag

fix: change refs to menu_from_projects to match new versioning scheme

---

docs/jobs/index.md
docs/jobs/profiles_downloader.md
docs/jobs/profiles_synchronizer.md
docs/schemas/profile/qgis_plugin.json
docs/schemas/profile/qgis_profile.json
docs/schemas/scenario/jobs/generic.json
docs/schemas/scenario/jobs/manage-env-vars.json
docs/schemas/scenario/jobs/qplugins-downloader.json
docs/schemas/scenario/jobs/qplugins-synchronizer.json
docs/schemas/scenario/jobs/qprofiles-downloader.json
docs/schemas/scenario/jobs/qprofiles-manager.json
docs/schemas/scenario/jobs/qprofiles-synchronizer.json
docs/schemas/scenario/jobs/shortcuts-manager.json
docs/schemas/scenario/jobs/splash-screen-manager.json
docs/schemas/scenario/metadata.json
docs/schemas/scenario/schema.json
docs/schemas/scenario/settings.json
examples/scenarios/demo-scenario-http.qdt.yml
examples/scenarios/demo-scenario.qdt.yml
qgis_deployment_toolbelt/jobs/job_profiles_downloader.py
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/jobs/orchestrator.py
scenario.qdt.yml
tests/fixtures/scenarios/good_scenario_profiles_http.yml
tests/fixtures/scenarios/good_scenario_profiles_only_different.qdt.yml
tests/fixtures/scenarios/good_scenario_profiles_only_missing.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml
tests/fixtures/scenarios/good_scenario_splash_screen_remove.qdt.yml
tests/fixtures/scenarios/good_scenario_with_unexisting_jobs.qdt.yml

This PR is part of #343 and of a whole refactoring.
In this PR:
- deprecating `qprofiles-manager`
- update related documentation and JSON schemas
- remove some outdated source code
Before:
```yaml
[...]
steps:
- name: Download profiles from remote git repository and synchronize with installed profiles
uses: qprofiles-manager
with:
source: https://github.com/Guts/qgis-deployment-cli.git
protocol: git_remote
sync_mode: overwrite
branch: main
[...]
```
After:
```yaml
[...]
steps:
- name: Download profiles from remote git repository
uses: qprofiles-downloader
with:
source: https://github.com/Guts/qgis-deployment-cli.git
protocol: git_remote
branch: main
- name: Synchronize downloaded profiles with installed ones
uses: qprofiles-synchronizer
with:
sync_mode: overwrite
[...]
```

Refacto: split profiles sync job

---

docs/jobs/environment_variables.md
qgis_deployment_toolbelt/jobs/job_environment_variables.py
qgis_deployment_toolbelt/utils/linux_utils.py
tests/dev/dev_manage_persistent_env_var_linux.py
tests/dev/dev_manage_persistent_env_var_windows.py
tests/fixtures/scenarios/good_scenario_sample.qdt.yml
tests/fixtures/scenarios/scenario_sample_as_admin.qdt.yml
tests/test_cli_main.py
tests/test_job_environment_variables.py
tests/test_utils_linux.py

Feature: job environment variables support linux

---

docs/guides/howto_behind_proxy.md
docs/guides/howto_use_custom_ssl_certs.md
docs/index.md
docs/usage/settings.md
qgis_deployment_toolbelt/utils/file_downloader.py
qgis_deployment_toolbelt/utils/journalizer.py
requirements/base.txt

By default, a bundle of SSL certificates is used, through [certifi](https://pypi.org/project/certifi/). This PR allows QDT to use the system certificates store.
In this PR:
- add [truststore](https://truststore.readthedocs.io/en/latest/#using-truststore-with-requests) as dependency to use new Python APIs (3.10) to deal with native system certs stores
- add a new `QDT_SSL_USE_SYSTEM_STORES` environment variable to enable this feature as an opt-in
- add related documentation
Related documentation: https://guts.github.io/qgis-deployment-cli/guides/howto_behind_proxy.html#id1
cc @DeCiZoR and @Niarolf

Feature: network use native system stores

---

setup.cfg
setup.py

Until now, it's still possible to install on unsupported Python versions.

packaging: set Python min/max versions

---

.github/workflows/tests.yml
examples/profiles/Viewer Mode/QGIS/QGIS3.ini
examples/profiles/demo/QGIS/QGIS3.ini
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/profiles/qdt_profile.py
qgis_deployment_toolbelt/profiles/qgis_ini_handler.py
qgis_deployment_toolbelt/utils/ini_interpolation.py
tests/test_qgis_ini_helper.py
tests/test_utils_ini_interpolation.py

- add write of environnement variable in .ini files with implementation of `before_write` in `EnvironmentVariablesInterpolation`
- add merge of `QdtProfile` from installed QGIS folder and downloaded one:
- copy download folder to temporary folder
- copy available .ini files from installed QGIS folder
- merge .ini from download folder and backup updated values
closes #451

feat(env variable): add write of environnement variable in .ini files from QDT profile

---

qgis_deployment_toolbelt/jobs/job_environment_variables.py

closes #451 
Local python environment variable was not updated by `manage-env-vars` job.
The added/removed variable could not be resolved when reading/writing .ini files.

fix(env variable): update local environment

---

docs/jobs/index.md
docs/jobs/qgis_installation_finder.md
docs/schemas/scenario/jobs/generic.json
docs/schemas/scenario/jobs/qgis-installation-finder.json
docs/usage/settings.md
examples/scenarios/demo-scenario-http.qdt.yml
examples/scenarios/demo-scenario.qdt.yml
qgis_deployment_toolbelt/exceptions.py
qgis_deployment_toolbelt/jobs/job_qgis_installation_finder.py
qgis_deployment_toolbelt/jobs/orchestrator.py
tests/test_job_qgis_installation_finder.py

related #273
- add job `qgis-installation-finder`
- search for QGIS installation in default installation folder:
- with `which` on Linux
- `%PROGRAMFILES%` on Windows
- new env var `QDT_OSGEO4W_INSTALL_DIR` for OSGeo4W (default `C:\\OSGeo4W`)
- define QGIS binary version with `--version` and string parsing
- add option for version in priority

feat(installed qgis): add qgis-installation-finder job

---

builder/version_info_templater.py

This PR makes it possible to have compliant SemVer versions.

enhancement: improve reliability of version templater making sure that a SemVer compliant version number is passed

---

qgis_deployment_toolbelt/jobs/job_splash_screen.py

Following #481, this PR fixes the case where a profile is not installed because of not matching defined rules but QDT is failing because of Splash Screen job tries to log a `profile.name` that does not exist in that case:
```python
2024-04-18 15:40:56||ERROR||check_path||check_path_exists||145||C:\Users\runneradmin\AppData\Roaming\QGIS\QGIS3\profiles\QDT Only Linux\QGIS\QGIS3.ini doesn't exist. Attempt 2/2. Game over.
2024-04-18 15:40:56||INFO||qgis_ini_handler||__init__||117||The specified file does not exist: C:\Users\runneradmin\AppData\Roaming\QGIS\QGIS3\profiles\QDT Only Linux\QGIS\QGIS3.ini.
2024-04-18 15:40:56||INFO||job_splash_screen||run||135||No profile.json found for profile 'C:\Users\runneradmin\.cache\qgis-deployment-toolbelt\repositories\qdt-demo-scenario\examples\profiles\on …
```

fix(logs): unreachable profile-attributes in logs

---

.gitignore
docs/conf.py
docs/development/documentation.md
docs/reference/qdt_profile.md

In this PR we generate the rules context dynamically for the documentation using a Sphinx hook. Then it's embedded like this:
To merge after #484.

Docs: add rules context dynamically

---

qgis_deployment_toolbelt/utils/user_groups.py
requirements/base.txt
tests/dev/dev_win_user_groups.py

Feature: retrieve win32 user groups

---

docs/conf.py
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/utils/computer_environment.py

```json
[...]
"user": {
"groups_domain": [],
"groups_local": [
"adm",
"cdrom",
"dip",
"docker",
"lpadmin",
"lxd",
"microk8s",
"plugdev",
"sambashare",
"sudo",
"vboxusers",
"www-data"
],
"name": "jmo"
}
```

feature(rules): add user name and groups to rules context

---

qgis_deployment_toolbelt/profiles/rules_context.py
qgis_deployment_toolbelt/utils/user_groups.py
qgis_deployment_toolbelt/utils/win32utils.py

This PR follows the 0.34 release to extend information when QDT is run in a Windows domain. Sample output:
```json
{
"date": {
"current_day": 24,
"current_month": 4,
"current_weekday": 2,
"current_year": 2024
},
"environment": {
"computer_network_name": "VM200145",
"linux_distribution_name": null,
"linux_distribution_version": null,
"operating_system_code": "win32",
"operating_system_release": "10",
"processor_architecture": "AMD64",
"windows_edition": "Professional"
},
"user": {
"groups_domain": [
"GGD_FONC_HENRY-TMA",
"GGD_ORGA_INTERVENANTS",
"GGD_ORG_DG-HENRY_DES",
"GGD_ORG_DG_TOUS",
"GGD_SCM_PMAD-SI",
"GGD_WIFI_AGENTS_TOUS",
"GG_INSTALL_SAGE_EAU",
"METROPOLIS_TOUS",
"SITE_DOMICILE-BUREAU_SOCIETE_EXTERNE",
"Tous_DDR",
"Tous_HENRY",
"Tous_HENRY_DINSI"
],
"groups_local": [],
"name": …
```

feature(rules): retrieve user extended data using win32 API

---

docs/guides/howto_use_custom_ssl_certs.md

fix(docs): value must be quoted in PowerShell command to set env vars

---

docs/usage/settings.md
qgis_deployment_toolbelt/commands/deployment.py
qgis_deployment_toolbelt/commands/upgrade.py
qgis_deployment_toolbelt/jobs/job_plugins_downloader.py
qgis_deployment_toolbelt/profiles/remote_http_handler.py
qgis_deployment_toolbelt/utils/file_downloader.py
tests/test_utils_file_downloader.py

This PR introduces a new option `QDT_STREAMED_DOWNLOADS` to control over stream mode for file downloader. By default, files are streamed but it can lead to some errors. This setting helps to avoid buggy behaviors.

feature(downloader): add option to control over stream mode

---

qgis_deployment_toolbelt/utils/file_downloader.py
tests/dev/dev_http_network_check.py

This PR follows up:
- https://github.com/Guts/qgis-deployment-cli/pull/544
- https://github.com/Guts/qgis-deployment-cli/pull/444
It improve how system's store certificates are used, preferring a custom HTTP adapter to the SSL injection.
It's mainly inspired from https://stackoverflow.com/a/78265028/2556577.

improve(downloader): use a custom HTTP transport adapter instead of rough injection

---

qgis_deployment_toolbelt/jobs/job_plugins_downloader.py

When `force: true` in plugins downloader job, it was failing because of unbound locale var:
```python
2024-09-04 10:03:43||ERROR||bouncer||exit_cli_error||43||cannot access local variable 'qdt_plugins_to_copy' where it 
is not associated with a value
Traceback (most recent call last):
File "qgis_deployment_toolbelt\commands\deployment.py", line 207, in run
File "qgis_deployment_toolbelt\jobs\job_plugins_downloader.py", line 120, in run
UnboundLocalError: cannot access local variable 'qdt_plugins_to_copy' where it is not associated with a value
```

fix(downloader): qdt_plugins_to_copy was not created in force mode

---

tests/fixtures/scenarios/good_scenario_plugins_downloader_force.qdt.yml

Following up https://github.com/Guts/qgis-deployment-cli/pull/551

improve(tests): add scenario to test against plugins downloader in monothread and forced

---

docs/jobs/qgis_installation_finder.md
docs/schemas/scenario/jobs/qgis-installation-finder.json
examples/scenarios/demo-scenario-http.qdt.yml
examples/scenarios/demo-scenario.qdt.yml
qgis_deployment_toolbelt/constants.py
qgis_deployment_toolbelt/jobs/job_qgis_installation_finder.py
scenario.qdt.yml
tests/dev/dev_qgis_install_version.py

Close #523 
Search of QGIS installed binary is now done recursively from a list of search paths.

Feature: support `search_paths` option in QGIS finder job

---

qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py

closes #531 
related #519
When `sync_mode` was `overwirte` we were still making merge to get new values for .ini.
Now in `overwrite` mode, a copy is done.

fix(profile sync): force copy if sync_mode is overwirte

---

docs/guides/howto_behind_proxy.md
docs/usage/settings.md
qgis_deployment_toolbelt/commands/upgrade.py
qgis_deployment_toolbelt/profiles/remote_http_handler.py
qgis_deployment_toolbelt/utils/file_downloader.py
qgis_deployment_toolbelt/utils/proxies.py
requirements/base.txt
tests/dev/dev_download_file_proxies.py
tests/test_utils_proxies.py

Introduce support for PAC file for proxy definition.
QDT will first try to use `QDT_PROXY_HTTP` environment variable then new environment variable `QDT_PAC_FILE` for custom PAC file then system PAC if available.

feat(proxies): use pypac to use PAC file

---

requirements/base.txt

With latest version 0.36.0 of QDT there are no logs display on Windows.
This comes from an update of python-win-ad to 0.6.3 that cause log level of pyad to be used for all python package.
We limit version of python-win-ad to 0.6.2 to restore log display.
closes #585

fix(log): limit pyad to 0.6.2 for correct log level

---

qgis_deployment_toolbelt/profiles/profiles_handler_base.py
qgis_deployment_toolbelt/utils/proxies.py

When a proxy is needed for git clone, `dulwich` and high level interface `porcelain` only use environment variable for proxy definition : `HTTP_PROXY` / `HTTPS_PROXY`
In this PR we are :
- defining a wrapper for environment variable definition and backup
- use wrapper for all function using porcelain for git command

fix(proxies): define environment variable for proxy use for git clone

---

qgis_deployment_toolbelt/jobs/job_plugins_downloader.py

Some server might not consider plugin .zip as `application/zip` but `application/x-zip-compressed`. 
In this case, the server doesn't return the plugin .zip but an error page.
In this PR we add `application/x-zip-compressed` to the header `Accept` to fix this issue.

feat(plugin download): add application/x-zip-compressed for header Accept

---

tests/test_cli_upgrade.py

Example of failed job: https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/actions/runs/12087850915/job/33710161685

fix(test): make sure dl_url is a string

---

qgis_deployment_toolbelt/utils/proxies.py

- we restored only if variable defined
- need to remove if no variable defined

fix(proxy): HTTP_PROXY env variable was not removed after os_env_proxy wrapper

---

.vscode/settings.json
docs/schemas/profile/qgis_profile.json
docs/schemas/profile/rules.json
docs/schemas/scenario/jobs/qdt_job_base.json
docs/schemas/scenario/qdt_scenario.json

Docs: update json schemas

---

docs/schemas/profile/rules.json
docs/schemas/scenario/jobs/qgis-installation-finder.json

Few fixes for profile and scenario schema

Fix schemas

---

docs/schemas/scenario/jobs/qgis-installation-finder.json

Following up of #600 
Before:
> after PR #600
- the schema does not matches structure, so validation is not really working
- it's "visible" with missing tooltip when over on keywords
After this PR:
See visible tooltips when mouse hover

fix(docs): simplify JSON schema of job qgis-finder

---

.github/workflows/build_release.yml

See: https://github.com/actions/runner-images/issues/10721

update(ci): use macos-15 since macos-12 is deprecated

---

docs/schemas/scenario/qdt_scenario.json
docs/schemas/scenario/settings.json
qgis_deployment_toolbelt/commands/deployment.py
qgis_deployment_toolbelt/scenarios/scenario_reader.py

This PR:
- automatically remove `QDT_` prefix from scenario settings name
- log about it
- global improvement of scenario reader regarding the dev guidelines
- add missing recognized settings to JSON schemas
- add a pattern to prevent end-user write a setting with the `QDT_` prefix

Improve: automatically remove prefix from scenario env vars

---

docs/jobs/default_profile_setter.md
docs/jobs/index.md
docs/schemas/scenario/jobs/default-profile-setter.json
docs/schemas/scenario/jobs/qdt_job_base.json
docs/schemas/scenario/jobs/qplugins-synchronizer.json
docs/schemas/scenario/jobs/shortcuts-manager.json
qgis_deployment_toolbelt/jobs/generic_job.py
qgis_deployment_toolbelt/jobs/job_default_profile_setter.py
qgis_deployment_toolbelt/jobs/job_shortcuts.py
qgis_deployment_toolbelt/jobs/orchestrator.py
tests/fixtures/scenarios/good_scenario_plugins_downloader_force.qdt.yml
tests/fixtures/scenarios/good_scenario_profiles_http.yml
tests/fixtures/scenarios/good_scenario_profiles_only_different.qdt.yml
tests/fixtures/scenarios/good_scenario_profiles_only_missing.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml
tests/fixtures/scenarios/good_scenario_splash_screen_remove.qdt.yml
tests/fixtures/scenarios/scenario_sample_as_admin.qdt.yml
tests/test_job_default_profile_setter.py
tests/test_job_generic.py
tests/test_utils_check_path.py

Fixes https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/issues/611
Some users might double-click on .qgs/.qgz project file. In this case, QGIS will be openned without `--profile` argument and `lastProfile` or `defaultProfile` in `profiles.ini` will be used which is unwanted, the deployed profile should be used

Add new job "default-profile-setter"

---

.github/workflows/build_release.yml
.github/workflows/lint.yml
.github/workflows/security.yml
.github/workflows/tests.yml

Closing https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Aactions%2Fmissing-workflow-permissions

update(ci): set GH permission scope to improve security

---

qgis_deployment_toolbelt/profiles/profiles_handler_base.py

`DESTINATION_BRANCH_TO_USE` 
- is "declared" as a string
https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/blob/38859d135c7561f8b3bc2d6525405f64f56d4e1c/qgis_deployment_toolbelt/profiles/profiles_handler_base.py#L62
- is always populated with a string in : 
- __init__
- https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/blob/38859d135c7561f8b3bc2d6525405f64f56d4e1c/qgis_deployment_toolbelt/profiles/local_git_handler.py#L98-L104  
```python
def get_active_branch_from_local_repository(self, local_git_repository_path: Path | None = None) -> str:
```
- ...
Without this change, the type of this variable becomes mixed `str | bytes`
But indeed, it needs to be converted to bytes at some point ([here](https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/blob/38 …

Store decoded branch name instead of bytes

---

builder/template_win_exe_version_info.txt

Change FileDescription from [DESCRIPTION] to [TITLE]
Add Comments with [DESCRIPTION] content
Docs: https://learn.microsoft.com/en-us/windows/win32/menurc/string-str
Fixes #667

Packaging: use title as file description and description as comments for Windows Task Manager display name

---

pyproject.toml
qgis_deployment_toolbelt/profiles/profiles_handler_base.py
tests/test_git_handler_remote.py

Between 0.38.0 and 0.38.2, we bump dulwich from 0.22 to 0.24 and a lot happened between these 2 versions.
This fixes this issue: 
```powershell
PS > ./qdt.exe -s https://gitlab.com/isl-ingenierie/qgis/isl_qgis_profiles/-/raw/main/scenarios/scenario_isl_qdt.yml?ref_type=heads
ERROR:qgis_deployment_toolbelt.profiles.remote_git_handler:Specified branch 'main' has not been found in source repository (https://gitlab.com/isl-ingenierie/qgis/isl_qgis_profiles.git). Fallback to identified active branch: None.
```
Because porcelain.ls_remote now return LsRemoteResult and not a dict anymore.
dict logic has been kept for back compatibility
A test has been added too to prevent futur silent regression

Fix: RemoteProfilesHandlerBase.list_remote_branches for newer versions of dulwich.porcelain

---

qgis_deployment_toolbelt/profiles/profiles_handler_base.py

fix(logs): disable error raising about invalid repo

---

.github/workflows/build_release.yml
.github/workflows/documentation.yml
docs/conf.py
docs/index.md
qgis_deployment_toolbelt/__about__.py
qgis_deployment_toolbelt/cli.py
qgis_deployment_toolbelt/commands/upgrade.py

Since we're using setuptools_scm, version number is quite ugly in documentation. This PR adds logic to retrieve version from:
1. from GITHUB_REF (in context CI)
2. using local git command
3. fallback on package version
Local render:

Docs and upgrade: distinguish current version from last release
