qgis-deployment/qgis-deployment-toolbelt-cli

.vscode/settings.json
qgis_deployment_toolbelt/cli.py
qgis_deployment_toolbelt/commands/cli_environment.py
qgis_deployment_toolbelt/utils/environment_manager.py
qgis_deployment_toolbelt/utils/proxies.py
qgis_deployment_toolbelt/utils/slugger.py
requirements/base.txt
sample-deployment-config.json
tests/dev/dev_manage_persistent_env_var.py
tests/dev/win_create_shortcut.py

For now, manage environment variables using a deployment scenario JSON file.

Feature: set up system environment for QGIS

---

.github/labeler.yml
.github/release.yml
.vscode/settings.json
setup.cfg

- enforce isort use
- fix codecov config

Tooling: isort and codecov

---

qgis_deployment_toolbelt/cli.py
qgis_deployment_toolbelt/jobs/job_shortcuts.py
qgis_deployment_toolbelt/profiles/shortcuts.py
scenario.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml

- use shortcut module to dynamically create shortcut for QGIS profiles
- add a mechanism to retrieve icon using a simple filename
- ⚠️ it changes the scenario structure

Job: achieve shortcuts creation

---

qgis_deployment_toolbelt/profiles/shortcuts.py
tests/test_shortcuts.py

Shortcuts: fix error when icon path is not defined

---

qgis_deployment_toolbelt/jobs/job_environment_variables.py
qgis_deployment_toolbelt/profiles/shortcuts.py
qgis_deployment_toolbelt/utils/__init__.py
qgis_deployment_toolbelt/utils/str2bool.py
qgis_deployment_toolbelt/utils/win32utils.py
scenario.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml
tests/test_job_environment_variables.py
tests/test_jobs_launch.py

- allow use of special char `~` in scenario files
- add utils: str2bool and `get_env_var _from_win32_registry`
- extend tests

Enhancement: environment variables

---

docs/index.md
docs/jobs/index.md
docs/jobs/splash_screen_manager.md
qgis_deployment_toolbelt/jobs/job_splash_screen.py
qgis_deployment_toolbelt/jobs/orchestrator.py
qgis_deployment_toolbelt/profiles/qdt_profile.py
qgis_deployment_toolbelt/utils/win32utils.py
requirements/base.txt
scenario.qdt.yml
tests/fixtures/profiles/good_profile_complete.json
tests/fixtures/profiles/good_profile_minimal.json
tests/fixtures/scenarios/good_scenario_sample.qdt.yml
tests/test_qdt_profile_object.py

Add a new job to install or uninstall custom splash screen images in QGIS profiles.

Feature: job splash screen manager

---

.github/workflows/documentation.yml
docs/conf.py
requirements/documentation.txt

- Fix build removing sphinx-autodoc-typehints
- Bump to Python 3.10
- Do not push to GH Pages except on main or tags

Fix documentation build on CI

---

qgis_deployment_toolbelt/cli.py
tests/test_cli_main.py

Check the validity of the scenario file

---

qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/profiles/remote_git_handler.py
scenario.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml

Reduce ambiguity
Maybe related to #147

Allow to specify branch to clone/pull

---

.vscode/tasks.json
qgis_deployment_toolbelt/jobs/job_plugins_synchronizer.py
qgis_deployment_toolbelt/plugins/plugin.py
scenario.qdt.yml

Following #172 
It add the mechanism to unzip downloaded plugins into profiles when plugins are missing.

Feature: plugins synchronization part 2

---

docs/jobs/plugins_synchronizer.md
qgis_deployment_toolbelt/jobs/job_plugins_synchronizer.py
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/plugins/plugin.py
qgis_deployment_toolbelt/profiles/qdt_profile.py
requirements/base.txt
scenario.qdt.yml
tests/test_qplugin_object.py

Feature: plugins synchronization part 3 - Upgrade older plugins

---

qgis_deployment_toolbelt/cli.py
qgis_deployment_toolbelt/constants.py

Fix QGIS bin path retriever

---

qgis_deployment_toolbelt/jobs/job_environment_variables.py
qgis_deployment_toolbelt/utils/win32utils.py
requirements/base.txt
tests/test_job_environment_variables.py

Use built-in functions and remove dependency to py-setenv (which embeds click)

Refacto: remove dependency to py-setenv

---

docs/usage/cli.md
qgis_deployment_toolbelt/commands/deployment.py
qgis_deployment_toolbelt/commands/upgrade.py
qgis_deployment_toolbelt/utils/str2bool.py
tests/test_utils.py
tests/test_utils_str2bool.py

Feature: use environment variables to set arguments values

---

qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
tests/fixtures/scenarios/good_scenario_profiles_only_different.qdt.yml
tests/fixtures/scenarios/good_scenario_profiles_only_missing.qdt.yml
tests/fixtures/scenarios/good_scenario_sample.qdt.yml

Fix: outdated profiles should also be copied when sync_mode=only_different

---

qgis_deployment_toolbelt/cli.py

Add default subparser to allow direct run of deployment

---

qgis_deployment_toolbelt/commands/deployment.py

Improve how invalid YAML files are handled

---

docs/usage/settings.md
qgis_deployment_toolbelt/constants.py
qgis_deployment_toolbelt/jobs/orchestrator.py
qgis_deployment_toolbelt/scenarios/scenario_reader.py

Fix: env var obfuscated by lru cache

---

.github/workflows/documentation.yml
.pre-commit-config.yaml
requirements/base.txt
requirements/development.txt
requirements/documentation.txt
requirements/packaging.txt
tests/test_utils_file_downloader.py

Quality: extends tests against file downloader util

---

qgis_deployment_toolbelt/plugins/plugin.py

Improve log message during plugin version comparison

---

LICENSE
qgis_deployment_toolbelt/__about__.py
qgis_deployment_toolbelt/cli.py
setup.py

To make the project more open to other contributions.
https://choosealicense.com/licenses/apache-2.0/

Switch license from LGPL3 to Apache License 2

---

.vscode/extensions.json
.vscode/settings.json

To silent warnings and to make it more generic.

Tooling: update VS Code config

---

builder/pyinstaller_build_macos.py
builder/pyinstaller_build_ubuntu.py
builder/pyinstaller_build_windows.py

Avoiding conflicts in artifacts names

Packaging: add operating system name to build report

---

qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/profiles/git_handler_base.py
qgis_deployment_toolbelt/profiles/local_git_handler.py
qgis_deployment_toolbelt/profiles/remote_git_handler.py
qgis_deployment_toolbelt/utils/check_path.py
requirements/testing.txt
tests/dev/dev_dulwich_local.py
tests/dev/dev_dulwich_remote.py
tests/test_git_handler_local.py
tests/test_git_handler_remote.py
tests/test_qplugin_object.py
tests/test_utils_check_path.py

- git handlers are more generic
- local and remote git handlers are tested specifically 
closes #344

Git synchronization: global improvements

---

qgis_deployment_toolbelt/jobs/job_shortcuts.py

Fix: surround profile name with quotes to prevent space

---

qgis_deployment_toolbelt/utils/linux_utils.py
tests/dev/dev_manage_persistent_env_var_linux.py
tests/dev/job_environment_variables_linux.py

Allow to remove an environment variable (and block start/end)
Allow to update an environment variable (delete and replace)

Allow to remove/update an environment variable

---

docs/jobs/profiles_manager.md
docs/schemas/scenario/jobs/qprofiles-manager.json
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py

Related to https://github.com/Guts/qgis-deployment-cli/pull/351

docs: update qprofiles-manager with deprecated 'git' value

---

README.md

tooling: add SonarCloud badge

---

sonar-project.properties

To get more control on sources and Python versions

tooling: add SonarCloud configuration file

---

.github/labeler.yml
.github/workflows/pr-auto-labeler.yml
.vscode/settings.json

Supersedes https://github.com/Guts/qgis-deployment-cli/pull/388

CI: update autolabeler to v5

---

qgis_deployment_toolbelt/commands/deployment.py
qgis_deployment_toolbelt/constants.py
qgis_deployment_toolbelt/jobs/generic_job.py
qgis_deployment_toolbelt/jobs/job_profiles_synchronizer.py
qgis_deployment_toolbelt/jobs/job_shortcuts.py
qgis_deployment_toolbelt/profiles/qdt_profile.py
qgis_deployment_toolbelt/shortcuts/shortcuts.py
tests/test_cli_main.py
tests/test_cli_upgrade.py
tests/test_constants.py

Some fixes and clean up following https://github.com/Guts/qgis-deployment-cli/pull/421

Improve: cleanup OSConfig and refacto CLI's tests to run outside real QGIS profiles folder

---

.gitignore
builder/pyinstaller_build_ubuntu.py
qgis_deployment_toolbelt/shortcuts/shortcuts.py

Fix: shortcut template was bundled to the wrong path

---

docs/jobs/profiles_downloader.md
docs/jobs/profiles_manager.md
docs/jobs/profiles_synchronizer.md
tests/dev/dev_dulwich_remote.py
tests/test_git_handler_remote.py
tests/test_job_profiles_sync.py
tests/test_utils_check_path.py
tests/test_utils_user_groups.py

tests(usergroups): add unit tests against user groups module

---

examples/profiles/Viewer Mode/QGIS/QGIS3.ini
qgis_deployment_toolbelt/profiles/rules_context.py

Fix: rules context crash on certain Windows configuration

---

qgis_deployment_toolbelt/utils/user_groups.py

improve(user_groups): enforces user domain groups retrieval using user guid

---

examples/scenarios/demo-scenario-http.qdt.yml
examples/scenarios/demo-scenario.qdt.yml

fix(scenario): qgis-installation-finder accept if_not_found value warning and not warn.

---

.vscode/settings.json
docs/conf.py
docs/guides/howto_manage_private_git.md
requirements/documentation.txt
scripts/qdt_clone_pull_profiles.ps1

add(docs): how to make QDT work with private git repositories

---

.github/workflows/tests.yml
tests/fixtures/scenarios/good_scenario_with_prefixed_env_vars.qdt.yml

Following up https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/pull/605

improve(test): add case with a prefixed environment variable

---

docs/jobs/default_profile_setter.md
docs/schemas/scenario/jobs/default-profile-setter.json
qgis_deployment_toolbelt/jobs/job_default_profile_setter.py
tests/test_job_default_profile_setter.py

Extend default profile setter job with force_profile_selection_policy option

---

docs/development/testing.md
docs/jobs/profiles_downloader.md
qgis_deployment_toolbelt/profiles/profiles_handler_base.py

fix: correctly handle UNC paths

---

.github/workflows/tests.yml

Attempt to avoid to trigger integration tests on doc updates

---

README.md
docs/index.md

update(docs): publicize Matrix channel
